# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073fd3b4b4925e21c18baf4d5f0ee74a03ee84d34618b9bab06678efa7c0b31bfe6bfb176d8592ea129e94f4ce92b735a82d29f548f7b13eafe6eeabc2f604a2

test:
  secret_key_base: 7ce8037eac3b008bf56c632f3db889f098371f543b3b81b620b1286a20783850ac0deeaeeb6caa1df308f11fa96d3fa4486417bf29761c2ec5bc887362c26c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
